// Code generated by Kitex v0.4.2. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	service "github.com/lqf1215/kitex-demo/kitex_gen/service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetUserList(ctx context.Context, Req *service.GetUserListReq, callOptions ...callopt.Option) (r *service.GetUserListResp, err error)
	GetUserById(ctx context.Context, Req *service.GetUserByIdReq, callOptions ...callopt.Option) (r *service.UserData, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) GetUserList(ctx context.Context, Req *service.GetUserListReq, callOptions ...callopt.Option) (r *service.GetUserListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserList(ctx, Req)
}

func (p *kUserServiceClient) GetUserById(ctx context.Context, Req *service.GetUserByIdReq, callOptions ...callopt.Option) (r *service.UserData, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserById(ctx, Req)
}
